### ISSUE TITLE
Kurai soy Mel

### ISSUE THREAD

**Issue by Meli16-lab** [kurai021/animebot#6]
Kurai soy Mel, la amiga a la cual le encargaste tu bot y llevas mucho tiempo sin volver quiero saber que paso contigo porque siendo honesta muchas veces me prwgunte porque desapareciste y que se supone que debo hacer con tu bot

**Comment by kurai021** [comment]
Estoy volviendo a su desarrollo, me di cuenta de que varias funciones estaban rotas, busco reemplazar al menos la mayoría. Estoy haciendo pruebas en una comunidad pequeña para luego volver a lanzarlo a Anime Amino
